### PR TITLE
Fun cog

### PR DESCRIPTION
**Pull request by VG08**
So i made the cog system work and added fun cog

### CODE REVIEW

**Comment by Tindi12** [comment]
OK looks good to me, green light go ahead and merge, make sure not to conflict with the __init__.py

**Comment by Tindi12** [comment]
Waitt!! DONT MERGE YET!! WE HAVE 2 CONFLICTS!!
let us first resolve them

**Comment by VG08** [comment]
Fixed the conflict issue
I think it it correct now

**Comment by VG08** [comment]
I tested it
not problem with the bot, all things are working fin

**Pull request merged**
