### PR TITLE
Added Facts

### PR DESCRIPTION
**Pull request by 45i**
Try running this @Tindi12

### CODE REVIEW

**Comment by VG08** [comment]
Don't change 8ball, make a different command for it

**Comment by MrinmoyHaloi** [comment]
the command is 8ball. and your are making something else

**Comment by 45i** [comment]
> Don't change 8ball, make a different command for it

i didnt wait hold up

**Comment by VG08** [comment]
> the command is 8ball. and your are making something else

Yes mrinmoy is correct

**Comment by VG08** [comment]
> > Don't change 8ball, make a different command for it
> 
> i didnt wait hold up

You did

**Comment by 45i** [comment]
nvm i realized my mistake
pls wait

**Comment by MrinmoyHaloi** [comment]
ok

**Comment by VG08** [comment]
You are changing this or making a new request?

**Comment by 45i** [comment]
so ill just make the _8ball to _fact right?

**Comment by 45i** [comment]
> You are changing this or making a new request?

adding a new feature

**Comment by MrinmoyHaloi** [comment]
> so ill just make the _8ball to _fact right?

yeah

**Comment by VG08** [comment]
No make a new command don't change an existing one

**Comment by 45i** [comment]
there

**Comment by VG08** [comment]
Also when you make a new one don't put name as _fact name it fact

**Comment by VG08** [comment]
> there

I meant to make a new command not change the existing one

**Comment by 45i** [comment]
> > there
> 
> I meant to make a new command not change the existing one

i didnt

**Comment by VG08** [comment]
You removed the existing command

**Comment by 45i** [comment]
> You removed the existing command

wat

**Comment by MrinmoyHaloi** [comment]
i am closing this. Make a new one after everything is fixed

**Comment by 45i** [comment]
> You removed the existing command

wait how?

**Comment by 45i** [comment]
i dont even know how to close a command

**Comment by MrinmoyHaloi** [comment]
i am closing it. Go and fix everything

**Comment by VG08** [comment]
> i dont even know how to remove a command

You changed the name and removed the contents

**Comment by VG08** [comment]
It is correct I couldn't see it correctly on phone

**Comment by VG08** [comment]
I will merge when brown approves

**Comment by VG08** [comment]
And I test it

**Comment by MrinmoyHaloi** [comment]
ok

**Comment by 45i** [comment]
> Also when you make a new one don't put name as _fact name it fact

Oh
I'll do it tomorrow

**Comment by 45i** [comment]
> I will merge when brown approves

Great!

**Comment by 45i** [comment]
> > Also when you make a new one don't put name as _fact name it fact
> 
> Oh
> I'll do it tomorrow

Nvm I did it 
Pls check someone

**Comment by VG08** [comment]
> > > Also when you make a new one don't put name as _fact name it fact
> > 
> > 
> > Oh
> > I'll do it tomorrow
> 
> Nvm I did it
> Pls check someone

Looks correct I will give full review tomorrow

**Comment by 45i** [comment]
> > > > Also when you make a new one don't put name as _fact name it fact
> > > 
> > > 
> > > Oh
> > > I'll do it tomorrow
> > 
> > 
> > Nvm I did it
> > Pls check someone
> 
> Looks correct I will give full review tomorrow

and test it too
cause i dont quite know if the bot can accept pypi packages not locally installed

**Comment by VG08** [comment]
> > > > > Also when you make a new one don't put name as _fact name it fact
> > > > 
> > > > 
> > > > Oh
> > > > I'll do it tomorrow
> > > 
> > > 
> > > Nvm I did it
> > > Pls check someone
> > 
> > 
> > Looks correct I will give full review tomorrow
> 
> and test it too
> cause i dont quite know if the bot can accept pypi packages not locally installed

all pypi packages will work when installed

**Comment by 45i** [comment]
> > > > > > Also when you make a new one don't put name as _fact name it fact
> > > > > 
> > > > > 
> > > > > Oh
> > > > > I'll do it tomorrow
> > > > 
> > > > 
> > > > Nvm I did it
> > > > Pls check someone
> > > 
> > > 
> > > Looks correct I will give full review tomorrow
> > 
> > 
> > and test it too
> > cause i dont quite know if the bot can accept pypi packages not locally installed
> 
> all pypi packages will work when installed

where?
Where are you going to install them?

**Comment by 45i** [comment]
because this is not a local bot running from one computer

**Comment by VG08** [comment]
> > > > > > > Also when you make a new one don't put name as _fact name it fact
> > > > > > 
> > > > > > 
> > > > > > Oh
> > > > > > I'll do it tomorrow
> > > > > 
> > > > > 
> > > > > Nvm I did it
> > > > > Pls check someone
> > > > 
> > > > 
> > > > Looks correct I will give full review tomorrow
> > > 
> > > 
> > > and test it too
> > > cause i dont quite know if the bot can accept pypi packages not locally installed
> > 
> > 
> > all pypi packages will work when installed
> 
> where?
> Where are you going to install them?

pip install package-name

**Comment by 45i** [comment]
> > > > > > > > Also when you make a new one don't put name as _fact name it fact
> > > > > > > 
> > > > > > > 
> > > > > > > Oh
> > > > > > > I'll do it tomorrow
> > > > > > 
> > > > > > 
> > > > > > Nvm I did it
> > > > > > Pls check someone
> > > > > 
> > > > > 
> > > > > Looks correct I will give full review tomorrow
> > > > 
> > > > 
> > > > and test it too
> > > > cause i dont quite know if the bot can accept pypi packages not locally installed
> > > 
> > > 
> > > all pypi packages will work when installed
> > 
> > 
> > where?
> > Where are you going to install them?
> 
> pip install package-name

ik that

**Comment by 45i** [comment]
pip install only installs it in a local directory right?

**Comment by VG08** [comment]
> pip install only installs it in a local directory right?

in local python

**Comment by 45i** [comment]
wait just to be clear
when a bot is run from say moscow, does it run the entire venv with it or just the code?

**Comment by VG08** [comment]
> wait just to be clear
> when a bot is run from say moscow, does it run the entire venv with it or just the code?

the venv is something that has to be installed the thing you will run is the bot

**Comment by 45i** [comment]
so when a bot is run (not locally) it **will** have the packages preinstalled right?

**Comment by 45i** [comment]
thats great then

**Pull request merged**
